[pkg.soumu]
tag = "総務省API"
msg = "入力中のコールサインを総務省APIで検索する拡張機能です"
web = "https://github.com/jucky154/soumuAPI"
use = ["dll.soumu"]
exp = "stable"

[pkg.cwtrain]
tag = "CW練習DLL"
msg = "zLogと同じ場所に置いたcallsigns.txtに書いたコールサインを自動的に流し、入力したコールサインと合致するかを判断するCW練習拡張機能です"
web = "https://github.com/jucky154/cwtrainer"
use = ["dll.cwtrain", "cfg.cwtrain", "dat.cwtrain", "txt.cwtrain"]
exp = "stable"

[pkg.infoEs]
tag = "Es通知プラグイン"
msg = "スポラディックE層の発生の有無を表示する拡張機能です"
web = "https://github.com/jucky154/infoEs"
use = ["dll.infoEs"]
exp = "stable"

[pkg.cwListener]
tag = "CW解析DLL"
msg = "CWの音声を自動的にデコードする拡張機能です。（アルファ版）"
web = "https://github.com/jucky154/cwListener"
use = ["dll.cwListener"]

[dll.soumu]
url = "https://github.com/jucky154/soumuAPI/releases/download/nightly/soumuAPI.dll"
sum = "https://github.com/jucky154/soumuAPI/releases/download/nightly/soumuAPI.dll.md5"

[dll.cwtrain]
url = "https://github.com/jucky154/cwtrainer/releases/download/nightly/cwtrainer.dll"
sum = "https://github.com/jucky154/cwtrainer/releases/download/nightly/cwtrainer.dll.md5"

[cfg.cwtrain]
url = "https://raw.githubusercontent.com/jucky154/cwtrainer/main/cwtrainer.cfg"

[dat.cwtrain]
url = "https://raw.githubusercontent.com/jucky154/cwtrainer/main/cwtrainer.dat"

[txt.cwtrain]
url = "https://raw.githubusercontent.com/jucky154/cwtrainer/main/callsigns.txt"

[dll.infoEs]
url = "https://github.com/jucky154/infoEs/releases/download/nightly/infoEs.dll"
sum = "https://github.com/jucky154/infoEs/releases/download/nightly/infoEs.dll.md5"

[dll.cwListener]
url = "https://github.com/jucky154/cwListener/releases/download/nightly/cwListener.dll"
sum = "https://github.com/jucky154/cwListener/releases/download/nightly/cwListener.dll.md5"

